version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.ueof.acme.dnschallenge=true"
      - "--certificatesresolvers.ueof.acme.dnschallenge.provider=gandiv5"
        # Remove acme.json if testing against stage then switching over
        #      - "--certificatesresolvers.ueof.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.ueof.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.ueof.acme.email=contact@burningdaylight.io"
      - "--certificatesresolvers.ueof.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "GANDIV5_API_KEY=
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.burningdaylight.io`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=ueof"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      # Must escape $ with $
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:"

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.burningdaylight.io`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=ueof"

  teamcity-db:
    image: postgres:9.6
    container_name: "teamcitydb"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=teamcity
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=teamcity
    volumes:
      - ./teamcity-postgres:/var/lib/postgresql/data

  teamcity-server:
    image: jetbrains/teamcity-server:2020.1.4
    container_name: "teamcity-server"
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/logs:/opt/teamcity/logs
    ports:
      - "8111:8111"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teamcity-server.rule=Host(`teamcity.burningdaylight.io`)"
      - "traefik.http.routers.teamcity-server.entrypoints=websecure"
      - "traefik.http.routers.teamcity-server.tls.certresolver=ueof"

  teamcity-agent:
    image: jetbrains/teamcity-agent:2020.1.4-linux-sudo
    container_name: "teamcity-arcade-agent"
    environment:
      - SERVER_URL=https://teamcity.burningdaylight.io
      - AGENT_NAME=arcade
      - DOCKER_IN_DOCKER=start
    volumes:
      - teamcity-agent:/data/teamcity_agent/conf
    privileged: true

  minio:
    image: minio/minio
    container_name: "minio"
    restart: unless-stopped
    command: server /data
    volumes:
      - "./minio/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.burningdaylight.io`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=ueof"
      - "traefik.http.middlewares.add-blog-bucket.addprefix.prefix=/static"
      - "traefik.http.middlewares.root-to-index.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.root-to-index.redirectregex.replacement=https://$$1/index.html"
      - "traefik.http.middlewares.pathing.chain.middlewares=root-to-index,add-blog-bucket"
      - "traefik.http.routers.blog.rule=Host(`blog.burningdaylight.io`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=ueof"
      - "traefik.http.routers.blog.middlewares=pathing"
    environment:
      - MINIO_SECRET_KEY=
      - MINIO_ACCESS_KEY=
      
  rockd:
    build:
      context: ./rockd-service
      dockerfile: Dockerfile
    ports:
      - '11012:8080'
    volumes:
      - /home/git/traefik2/rockd-service/rocksdb:/tmp/rocks
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rockd.rule=Host(`portal.burningdaylight.io`)"
      - "traefik.http.routers.rockd.entrypoints=websecure"
      - "traefik.http.routers.rockd.tls.certresolver=ueof"

  youtrack:
    image: jetbrains/youtrack:2020.3.9516
    container_name: "youtrack"
    volumes:
      - /home/git/traefik2/youtrack/data:/opt/youtrack/data
      - /home/git/traefik2/youtrack/conf:/opt/youtrack/conf
      - /home/git/traefik2/youtrack/logs:/opt/youtrack/logs
      - /home/git/traefik2/youtrack/backup:/opt/youtrack/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.youtrack.rule=Host(`youtrack.burningdaylight.io`)"
      - "traefik.http.routers.youtrack.entrypoints=websecure"
      - "traefik.http.routers.youtrack.tls.certresolver=ueof"
      - 
  cgit:
    build:
      context: ./cdgit
      dockerfile: Dockerfile
    ports:
      - 8181:80
    volumes:
      - /home/git/traefik2/git/home/repos:/srv/git
      - /home/git/traefik2/cgit/cgitrc:/etc/cgitrc
      - /home/git/traefik2/cgit/www/default.conf:/etc/nginx/sites-available/default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cgit.rule=Host(`git.burningdaylight.io`)"
      - "traefik.http.routers.cgit.entrypoints=websecure"
      - "traefik.http.routers.cgit.tls.certresolver=ueof"

  git:
    build:
      context: ./dgit
      dockerfile: Dockerfile
    ports:
      - '22:22'
    volumes:
      - /home/git/traefik2/git/home:/home/git
      - /home/git/traefik2/git/ssh:/etc/ssh
    restart: on-failure
    labels:
      - "traefik.tcp.routers.git-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.git-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.git-ssh.service=git-ssh-svc"
      - "traefik.tcp.services.git-ssh-svc.loadbalancer.server.port=22"

  sonarqube:
    image: sonarqube:8-community
    depends_on:
      - sonar-db
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=
      - sonar.jdbc.url=jdbc:postgresql://sonar-db/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - "9999:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonar.rule=Host(`sonar.burningdaylight.io`)"
      - "traefik.http.routers.sonar.entrypoints=websecure"
      - "traefik.http.routers.sonar.tls.certresolver=ueof"
 
  sonar-db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD:
    volumes:
      - /home/git/sonar-postgres:/var/lib/postgresql
      - /home/git/sonar-postgres:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  teamcity-agent:
    external: true
